# Generated by Django 4.0.4 on 2022-05-30 22:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_comment_body'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('Com', django.db.models.manager.Manager()),
            ],
        ),
    ]
